# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0045_add_reservable_days_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Key')),
                ('default_route', models.CharField(blank=True, max_length=500, null=True, verbose_name='Default route')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('purposes', models.ManyToManyField(blank=True, to='resources.Purpose', verbose_name='Purposes')),
                ('resources', models.ManyToManyField(blank=True, to='resources.Resource', verbose_name='Resources')),
                ('units', models.ManyToManyField(blank=True, to='resources.Unit', verbose_name='Units')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
