# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_add_access_code_fields_and_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
