# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0043_add_reservable_days_in_advance'),
        ('resources', '0043_add_description_to_purpose'),
    ]

    operations = [
    ]
