# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0044_merge_20161105_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservable_after_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable after days from today'),
        ),
        migrations.AddField(
            model_name='unit',
            name='reservable_after_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable after days from today'),
        ),
    ]
