# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_add_reservable_days_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_info_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_info_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation info'),
        ),
    ]
