# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_anonymize_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
        migrations.AddField(
            model_name='unit',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
    ]
