# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 04:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_favorite_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='KohaUserIdentifier',
            fields=[
                ('borrowernumber', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'koha identifiers',
                'verbose_name': 'koha identifier',
            },
        ),
        migrations.AddField(
            model_name='kohauseridentifier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koha_identifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
